version: "3"

services:
  router:
    build: ./containers/router
    env_file:
    - ./.env
    ports:
    - "${ROUTER_PORT}:80"
    depends_on:
    - api

  # API
  api:
    build: ./containers/api
    env_file:
    - ./.env
    volumes:
    - ./containers/api/src:/usr/src/app/src
    restart: always
  
  mongo:
    #volumes:
    #- ./mongo:/data/db
    logging:
      driver: none
    image: mongo
    env_file:
    - ./.env
    ports:
    - "27020:27017"